// <auto-generated />
using BirEylulMarket.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BirEylulMarket.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BirEylulMarket.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KategoriAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriAd = "İçecekler"
                        },
                        new
                        {
                            Id = 2,
                            KategoriAd = "Süt Ürünleri"
                        },
                        new
                        {
                            Id = 3,
                            KategoriAd = "Hırdavat"
                        },
                        new
                        {
                            Id = 4,
                            KategoriAd = "Yiyecek"
                        });
                });

            modelBuilder.Entity("BirEylulMarket.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("UrunAd")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirimFiyat = 4.50m,
                            KategoriId = 1,
                            UrunAd = "Kola"
                        },
                        new
                        {
                            Id = 2,
                            BirimFiyat = 2.50m,
                            KategoriId = 1,
                            UrunAd = "Soda"
                        },
                        new
                        {
                            Id = 3,
                            BirimFiyat = 3.50m,
                            KategoriId = 2,
                            UrunAd = "Ayran"
                        },
                        new
                        {
                            Id = 4,
                            BirimFiyat = 7.50m,
                            KategoriId = 2,
                            UrunAd = "Yoğurt"
                        },
                        new
                        {
                            Id = 5,
                            BirimFiyat = 12.50m,
                            KategoriId = 3,
                            UrunAd = "Çekiç"
                        },
                        new
                        {
                            Id = 6,
                            BirimFiyat = 9.50m,
                            KategoriId = 3,
                            UrunAd = "Çivi"
                        },
                        new
                        {
                            Id = 7,
                            BirimFiyat = 22.50m,
                            KategoriId = 4,
                            UrunAd = "Tavuk"
                        },
                        new
                        {
                            Id = 8,
                            BirimFiyat = 24.99m,
                            KategoriId = 4,
                            UrunAd = "Pizza"
                        });
                });

            modelBuilder.Entity("BirEylulMarket.Models.Urun", b =>
                {
                    b.HasOne("BirEylulMarket.Models.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("BirEylulMarket.Models.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
